version: "2"

services:

  web:
    build: ./docker/web
    links:
      - db
    depends_on:
      - db
    ports:
      - "8765:8765"
    volumes:
      - ./:/var/www/html
      - ./docker/web/conf.d/000-default.conf:/etc/apache2/sites-enabled/001-default.conf
    working_dir: /var/www/html
    environment:
      DATABASE_URL: "mysql://webappadmin:webapppw@db/webapp?timezone=Asia/Tokyo&encoding=utf8"
      APP_DEFAULT_LOCALE: "ja_JP"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      XDEBUG_CONFIG: remote_port=9001
    hostname: webhost

  db:
    build: ./docker/db
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./config/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webappadmin
      MYSQL_PASSWORD: webapppw
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: db

  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      -  ./docker/phpmyadmin/sessions:/sessions